version: '3'

tasks:
  default:
    desc: Default task - builds the CLI binary
    cmds:
      - task: build
  
  build:
    desc: Build the CLI binary
    cmds:
      - mkdir -p bin
      - go build -o bin/cctp ./cmd/cli
  
  test:
    desc: Run all tests
    cmds:
      - go test ./...
  
  test-verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...
  
  test-coverage:
    desc: Run all tests with coverage report
    cmds:
      - go test -cover ./...
  
  test-coverage-html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"
  
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin
      - rm -f coverage.out coverage.html

